[package]
name = "cve_2019_89242"
version = "0.1.0"
authors = ["Sylvain Kerkour <sylvain@kerkour.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls", "cookies", "multipart"] }
anyhow = "1.0"
chrono = "0.4"
regex = "1.5"
