[package]
name = "cve_2019_11229"
version = "0.1.0"
authors = ["Sylvain Kerkour <sylvain@kerkour.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "cookies"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
regex = "1.4"
tempfile = "3"
actix-web = "=4.0.0-beta.5"
actix-files = "0.6.0-beta.4"
# https://github.com/actix/actix-web/issues/2166
actix-service = "=2.0.0-beta.5"
rand = "0.8"
url = "2"
cookie = {version = "0.15", features = ["percent-encode"]}
